format = """
[](#8F2D10)\
$directory\
[](fg:#8F2D10)\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
$time\
"""
[directory]
style = "fg:#1D1B1A bg:#8F2D10"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#1D1B1A"
format = '[[ $symbol $branch ](fg:#8F2D10 bg:#1D1B1A)]($style)'

[git_status]
style = "bg:#1D1B1A"
format = '[[($all_status$ahead_behind )](fg:#8F2D10 bg:#1D1B1A)]($style)'

[nodejs]
symbol = ""
style = "bg:#1D1B1A"
format = '[[ $symbol ($version) ](fg:#8F2D10 bg:#1D1B1A)]($style)'

[rust]
style = "bg:#1D1B1A"
symbol = ""
format = '[[ $symbol ($version) ](fg:#8F2D10 bg:#1D1B1A)]($style)'

[golang]
symbol = ""
style = "bg:#1D1B1A"
format = '[[ $symbol ($version) ](fg:#8F2D10 bg:#1D1B1A)]($style)'

[php]
symbol = ""
style = "bg:#1D1B1A"
format = '[[ $symbol ($version) ](fg:#8F2D10 bg:#1D1B1A)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1D1B1A"
format = '[[  $time ](fg:#8F2D10 bg:#1D1B1A)]($style)'

