--print("Hello Carter, are you ready to code?")
require("core.keymaps")
require("core.lazy")
require("core.plugins")
require("core.theme")
require("core.plugin.telescope")
require("core.plugin.startup")
require("core.plugin.lualine")
require("core.plugin.treesitter")
require("core.plugin.nvimtree")
require("core.plugin.mason")
--require("core.plugin.completions")
